model:
  target: icm.models.in_context_matting.InContextMatting

  params:
    learning_rate: 0.0001

    use_scheduler: True
    loss_type: "smooth_l1" # "smooth_l1" or "vit_matte" or "cross_entropy" or "focal_loss"
    freeze_transformer: True

    scheduler_config:
      target: icm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [1] # NOTE for resuming. use 10000 if starting from scratch
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [1.]

data:
  target: icm.data.data_module.DataModuleFromConfig
  params:
    # train_batch_size is set here, validation_batch_size is 1
    batch_size: 8
    # train_loader_num_workers is set here, validation_loader_num_workers is 0
    num_workers: 0
    shuffle_train: False
    train:
      target: icm.data.data_generator.ContextDataset
      params:
        crop_size: 512
        phase: train
        data:
          target: icm.data.image_file.ContextData
          params:
            ratio: 0.9
            dataset_name:
              ["open-images-test","open-images-validation" ] # ["PPM", "AM2k", "RWP636", "P3M_val_np"]
    validation:
      target: icm.data.data_generator.ContextDataset
      params:
        crop_size: 512
        phase: val
        data:
          target: icm.data.image_file.ContextData
          params:
            ratio: 0
            dataset_name:
              ["icm57"]

trainer:
  accelerator: "ddp"
  gpus: 2
  max_epochs: 1000
  auto_select_gpus: False
  num_sanity_val_steps: 0
  plugins:
    target: pytorch_lightning.plugins.DDPPlugin
    params:
      find_unused_parameters: False
  # weights_summary: full

  cfg_logger:
    target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    params:
      save_dir: logs # set in main.py
      default_hp_metric: False

  cfg_callbacks:
    modelcheckpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        monitor: epoch
        mode: max
        save_top_k: 100
        every_n_epochs: 1
        # save_last: True
        # save_weights_only: False
        filename: "{epoch:02d}-{val/mse_all:.5f}-{val/mse_unknown:.5f}"
        auto_insert_metric_name: False
