data:
  target: icm.data.data_module.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    shuffle_train: False
    validation:
      target: icm.data.data_generator.InContextDataset
      params:
        crop_size: 512
        phase: train
        data:
          target: icm.data.image_file.ContextData
          params:
            ratio: 0.9
            dataset_name:
              ["open-images-test","open-images-validation" ] # ["PPM", "AM2k", "RWP636", "P3M_val_np"]
