data:
  target: icm.data.data_module.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    shuffle_train: False
    validation:
      target: icm.data.data_generator.InContextDataset
      params:
        crop_size: 768
        phase: train
        norm_type: "sd" # "imagenet" or "sd"
        data:
          target: icm.data.image_file.ContextData
          params:
            ratio: 1
            dataset_name:
              ["ICM57" ] # ["PPM", "AM2k", "RWP636", "P3M_val_np"]
