model:
  target: icm.models.in_context_matting_.InContextMatting
  params:
    learning_rate: 0.0004

    cfg_loss_function:
      target: icm.models.criterion.loss_function.LossFunction
      params:
        losses: [
            "unknown_l1_loss",
            "known_l1_loss",
            "loss_pha_laplacian",
            "loss_gradient_penalty",
            # "smooth_l1_loss",
            # "cross_entropy_loss",
            # "focal_loss",
          ]

    cfg_scheduler:
      target: icm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [250] # NOTE 1 for resuming. use 250 if starting from scratch
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [1.]

    cfg_feature_extractor:
      target: icm.src.models.dift_sd.FeatureExtractor
      params:
        sd_id: "pretrained_models/stable-diffusion-2-1"
        load_local: True
        if_softmax: 1
        feature_index_cor: 1
        feature_index_matting: 1
        attention_res: 48 # [24， 48]
        set_diag_to_one: True
        time_steps: [0]
        extract_feature_inputted_to_layer: False
        ensemble_size: 8

    cfg_in_context_decoder:
      target: icm.models.decoder.in_context_decoder.InContextDecoder
      params:
        freeze_in_context_fusion: False # True for finetuning
        cfg_detail_decoder:
          target: icm.models.decoder.detail_capture.DetailCapture
          params:
            use_sigmoid: True
            ckpt: ""
            in_chans: 1280
            img_chans: 4
            convstream_out: [48, 96, 192]
            fusion_out: [256, 128, 64, 32]
        cfg_in_context_fusion:
          target: icm.models.decoder.in_context_correspondence.TrainingFreeAttentionBlocks
          params:
            res_ratio: 8
            pool_type: "min"
            temp_softmax: 1
            use_scale: True
            upsample_mode: "bicubic"
            bottle_neck_dim: None
            use_norm: 1280

data:
  target: icm.data.data_module.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    shuffle_train: False
    train:
      target: icm.data.data_generator.InContextDataset
      params:
        crop_size: 768
        phase: train
        norm_type: "sd" # "imagenet" or "sd"
        data:
          target: icm.data.image_file.ContextData
          params:
            ratio: 1
            dataset_name: [ "AIM-ICM", 
                # "open-images-test",
                # "open-images-validation",
                # "open-images-train_0",
              ] # ["PPM", "AM2k", "RWP636", "P3M_val_np"]
    validation:
      target: icm.data.data_generator.InContextDataset
      params:
        crop_size: 768
        phase: val
        norm_type: "sd" # "imagenet" or "sd"
        data:
          target: icm.data.image_file.ContextData
          params:
            ratio: 0
            dataset_name: [
                "ICM57",
                # "open-images-test",
                # "open-images-validation",
                # "open-images-train_0",
              ]

trainer:
  check_val_every_n_epoch: 5
  accelerator: "ddp"
  gpus: 1
  max_epochs: 1000
  auto_select_gpus: False
  num_sanity_val_steps: 0
  plugins:
    target: pytorch_lightning.plugins.DDPPlugin
    params:
      find_unused_parameters: False
  # weights_summary: full

  cfg_logger:
    target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    params:
      save_dir: logs # set in main.py
      default_hp_metric: False

  cfg_callbacks:
    modelcheckpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        monitor: epoch
        mode: max
        save_top_k: 100
        every_n_epochs: 1
        # save_last: True
        # save_weights_only: False
        filename: "{epoch:02d}-{val/mse_all:.5f}"
        auto_insert_metric_name: False
